#  Copyright (C) 2018-2021 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# Configuration file for Sonar Scanner used for CI 

sonar.projectKey=usdot-fhwa-stol_autoware-ai
sonar.organization=usdot-fhwa-stol
sonar.cfamily.cache.enabled=false
sonar.cfamily.compile-commands=/opt/carma/build/compile_commands.json
sonar.host.url=https://sonarcloud.io
sonar.cfamily.gcov.reportsPath=/opt/carma/coverage_reports/gcov
sonar.coverageReportPaths=/opt/carma/coverage_reports/gcov/coverage.xml
sonar.cpp.file.suffixes=.cpp,.h,.tpp
sonar.c.file.suffixes=-
# Exclude any Java files so Sonar doesn't demand .class artifacts:
sonar.exclusions=**/*.java
# Set Git as SCM sensor
sonar.scm.disabled=false
sonar.scm.enabled=true
sonar.scm.provider=git
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
# # This should match the AUTOWARE_PACKAGE_SELECTION variable in the carma_autoware_build script but with out msg packages

sonar.modules= dead_reckoner, \
  hardcoded_params, \
  lanelet2, \
  lanelet2_core, \
  lanelet2_examples, \
  lanelet2_extension, \
  lanelet2_io, \
  lanelet2_maps, \
  lanelet2_matching, \
  lanelet2_projection, \
  lanelet2_python, \
  lanelet2_routing, \
  lanelet2_traffic_rules, \
  lanelet2_validation, \
  lidar_localizer_ros2, \
  map_file_ros2, \
  points_downsampler, \
  twist_filter, \
  twist_gate

dead_reckoner.sonar.projectBaseDir        = /opt/carma/src/autoware.ai/core_perception/dead_reckoner
hardcoded_params.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/common/hardcoded_params
lanelet2.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2
lanelet2_core.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_core
lanelet2_examples.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_examples
lanelet2_extension.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/common/lanelet2_extension
lanelet2_io.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_io
lanelet2_maps.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_maps
lanelet2_matching.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_matching
lanelet2_projection.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_projection

lanelet2_python.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_python
lanelet2_routing.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_routing
lanelet2_traffic_rules.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_traffic_rules
lanelet2_validation.sonar.projectBaseDir    = /opt/carma/src/autoware.ai/lanelet2_validation
lidar_localizer_ros2.sonar.projectBaseDir     = /opt/carma/src/autoware.ai/core_perception/lidar_localizer_ros2
map_file_ros2.sonar.projectBaseDir            = /opt/carma/src/autoware.ai/common/map_file_ros2
points_downsampler.sonar.projectBaseDir  = /opt/carma/src/autoware.ai/core_perception/points_downsampler
twist_filter.sonar.projectBaseDir        = /opt/carma/src/autoware.ai/core_planning/twist_filter
twist_gate.sonar.projectBaseDir        = /opt/carma/src/autoware.ai/core_planning/twist_gate


# # C++ Package differences
dead_reckoner.sonar.sources=.
hardcoded_params.sonar.sources=.
lanelet2.sonar.sources=.
lanelet2_core.sonar.sources=.
lanelet2_examples.sonar.sources=.
lanelet2_extension.sonar.sources=.
lanelet2_io.sonar.sources=.
lanelet2_maps.sonar.sources=.
lanelet2_matching.sonar.sources=.
lanelet2_projection.sonar.sources=.
lanelet2_python.sonar.sources=.
lanelet2_routing.sonar.sources=.
lanelet2_traffic_rules.sonar.sources=.
lanelet2_validation.sonar.sources=.
lidar_localizer_ros2.sonar.sources=.
map_file_ros2.sonar.sources=.
points_downsampler.sonar.sources=.
twist_filter.sonar.sources=.
twist_gate.sonar.sources=.