# This workflow will build and push official docker images when new push occurs to develop, master, release branches but doesn't run any unit test or sonar scanner
name: Docker Hub build

on:
  push:
    branches:
      - "carma-develop"
      - "master"
      - "release/*"
jobs:
  dockerhub:
    runs-on: ubuntu-latest-8-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: usdotfhwastoldev/${{ github.event.repository.name }}:develop      